export const restaurants = [
  {
    name: "Darko's Grill",
    description: "",
    addresss: "",
    menu: "meat",
    rating: "",
    logo: "",
    main_image: "",
    _id: "",
  },
  {
    name: "Simaian Salad Store",
    description: "",
    addresss: "",
    menu: "salads",
    rating: "",
    logo: "",
    main_image: "",
    _id: "",
  },
  {
    name: "Sandy Pirates Seafood Store",
    description: "",
    addresss: "",
    menu: "seaFood",
    rating: "",
    logo: "",
    main_image: "",
    _id: "",
  },
];
